# Generated by Django 5.0.7 on 2024-08-07 16:20

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='myapp/img/')),
                ('url', models.URLField(blank=True)),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
