# Generated by Django 5.0.7 on 2024-08-07 16:56

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='myapp/img/')),
                ('url', models.URLField(blank=True)),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
