# Generated by Django 5.0.7 on 2024-08-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_delete_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='services/img/'),
        ),
    ]
